CREATE TABLE TB_USER (
                         id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         email VARCHAR2(255),
                         password VARCHAR2(255),
                         role VARCHAR2(255)
);