CREATE TABLE TB_CHMOTTU_PATIO (
                                  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  nome VARCHAR2(255) NOT NULL,
                                  capacidade_maxima NUMBER(10) NOT NULL,
                                  area_total FLOAT(53) NOT NULL,
                                  observacoes VARCHAR2(1000),
                                  CONSTRAINT chk_patio_capacidade CHECK (capacidade_maxima >= 1),
                                  CONSTRAINT chk_patio_area CHECK (area_total > 0)
);

CREATE TABLE TB_CHMOTTU_MOTO (
                                 id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 modelo VARCHAR2(100) NOT NULL,
                                 placa VARCHAR2(255) NOT NULL UNIQUE,
                                 chassi VARCHAR2(255) NOT NULL UNIQUE,
                                 ativa NUMBER(1) NOT NULL,
                                 status_sensor VARCHAR2(255),
                                 andar VARCHAR2(50),
                                 vaga VARCHAR2(50),
                                 localizacao_atual_latitude NUMBER(10, 8),
                                 localizacao_atual_longitude NUMBER(10, 8),
                                 patio_id NUMBER,
                                 CONSTRAINT fk_moto_patio FOREIGN KEY (patio_id) REFERENCES TB_CHMOTTU_PATIO(id),
                                 CONSTRAINT chk_moto_ativa CHECK (ativa IN (0, 1))
);